homeassistant:
  name: My Home
  country: RU
  currency: RUB
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 5
  unit_system: metric
  time_zone: Europe/Moscow
  # Customization file
#  customize: !include_dir_merge_named includes/customize
  packages: !include_dir_merge_named includes/packages
  
# Loads default set of integrations. Do not remove.
#default_config:
  allowlist_external_dirs :
   - /config

# For HomeKit
#zeroconf:

config:
#Сканирование доступных устройств в сети
ssdp:

# блютус
#bluetooth:
#device_tracker:
#  - platform: bluetooth_le_tracker
#    track_new_devices: true

# Включение официального интерфейса
frontend:
  themes: !include_dir_merge_named themes
  
  extra_module_url:
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/button-card/button-card.js
    - /hacsfiles/weather-radar-card/weather-radar-card.js
    - /hacsfiles/lovelace-state-switch/state-switch.js
    - /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
    - /hacsfiles/light-entity-card/light-entity-card.js
    - /hacsfiles/my-cards/my-cards.js
    - /hacsfiles/bar-card/bar-card.js


template: !include sidebar.yaml

# Включение карты
#map:
#Панель энергия
energy:
# Журнал событий
logbook:
# Включение поддержки приложения
mobile_app:
# Отслеживание солнца
sun:
# API для предоставления информации о системе и ее компонентах
system_health:
# Stream from camera
stream:
history:
    

# Reverse Proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 172.21.0.0/24
  - 192.168.10.0/24
  - 192.168.1.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5
#  api_password: !secret http_api_password
  
#panel_iframe:
#  configurator:
#    title: Configurator
#    icon: mdi:wrench
#    url: https://ha-conf.romchik.keenetic.pro/
#    require_admin: true 
#  duplicati:
#    title: "Duplicati"
#    icon: mdi:backup-restore
#    url: http://192.168.1.100:8201
#    require_admin: true
#  zigbee2mqtt:
#    title: "Zigbee2mqtt"
#    url: "https://z2m.romchik.keenetic.pro/#/"
#    icon: mdi:zigbee
#    require_admin: true
#  vscode:
#    title: "VisualCode"
#    url: "https://vsc.romchik.keenetic.pro/"
#    icon: mdi:microsoft-visual-studio-code
#    require_admin: true
#  grocy:
#    title: "Grocy"
#    url: "https://googleweblight.com/?lite_url=http://192.168.1.100:9283"
#    icon: phu:garbage-residual
#    require_admin: false
#  nodered:
#    title: Node-RED
#    icon: mdi:lan
#    url: "https://nodered.romchik.keenetic.pro/"
#    require_admin: true

#Локальный режим для Яндекс станции
yandex_station:
  devices:
    !secret ya_mini_id :
      host: 192.168.3.4
    !secret ya_max_id :
      host: 192.168.3.20    

  media_players:
    - entity_id: media_player.samsung_q60ba_55_tv
      name: SamsungTV
#      media_content_type: url  # важно для интеграции SamsungTV из HACS
    - entity_id: media_player.tox1_150
      name: Tox
#    - entity_id: media_player.tox1_150_ap
#      name: Tox Apple     
#      sync_volume: False  # опциональное отключение синхронизации громкости звука

# Медиа контент
#media_source:

lovelace:
  mode: yaml
  resources:
    [
      { url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,           type: module },
      { url: /hacsfiles/ha-yandex-icons/yandex-icons.js,                         type: module },
      { url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,               type: module },
      { url: /hacsfiles/stack-in-card/stack-in-card.js,                          type: module },
      { url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js,               type: module },
      { url: /hacsfiles/air-visual-card/air-visual-card.js,                      type: module },
      { url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js,     type: module },
      { url: /hacsfiles/lovelace-auto-entities/auto-entities.js,                 type: module },
      { url: /hacsfiles/battery-state-card/battery-state-card.js,                type: module },
      { url: /hacsfiles/history-explorer-card/history-explorer-card.js,          type: module },
      { url: /hacsfiles/weather-card/weather-card.js,                            type: module },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js,                           type: module },
      { url: /hacsfiles/logbook-card/logbook-card.js,                            type: module },
      { url: /hacsfiles/home-assistant-jukebox/jukebox-card.js,                  type: module },
      { url: /hacsfiles/timer-bar-card/timer-bar-card.js,                        type: module },
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                      type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                     type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                                type: module },
      { url: /hacsfiles/lovelace-hourly-weather/hourly-weather.js,               type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                type: module },
      { url: /hacsfiles/hass-swipe-navigation/swipe-navigation.js,               type: module },
      { url: /hacsfiles/decluttering-card/decluttering-card.js,                  type: module },
      { url: /hacsfiles/lovelace-flower-card/flower-card.js,                     type: module },
      { url: /hacsfiles/ha-sankey-chart/ha-sankey-chart.js,                      type: module },
      { url: /hacsfiles/miflora-card/miflora-card.js,                            type: module },
    ]


#    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
#      type: js
#    - url: /hacsfiles/entity-attributes-card/entity-attributes-card.js
#      type: module 
#    - url:  /hacsfiles/vacuum-card/vacuum-card.js
#      type: module 
#    - url: /hacsfiles/light-entity-card/light-entity-card.js
#      type: module      

  dashboards:
    lovelace-graph:
      mode: yaml
      filename: ui_graph.yaml
      title: Графики
      icon: mdi:chart-bell-curve-cumulative
      show_in_sidebar: true
      require_admin: true
      
#    lovelace-panel:
#      mode: yaml
#      filename: ui_panel.yaml
#      title: Планшет
#      icon: mdi:tablet-dashboard
#      show_in_sidebar: true
#      require_admin: false

    lovelace-tablet:
      mode: yaml
      filename: ui-lovelace_tablet.yaml
      title: Планшет new
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      require_admin: false

telegram_bot:
  - platform: polling
    api_key: !secret api_key_bot
#    parse_mode: html # иначе ошибка с подчеркиваниями _
    allowed_chat_ids:
      - !secret chat_id_romchik
      - !secret chat_id_kitka
      - !secret chat_id_group
      - !secret chat_id_group_alarm
     

# Включение кнопок ввода
input_button:
#input_datetime:
#Включение записи в mariaDB
#recorder:


#Вынос в файлы
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
#automation: !include includes/automations.yaml
yandex_smart_home: !include includes/yandex_smart_home.yaml
yandex_station_intents: !include includes/yandex_station_intents.yaml
#yandex_music_browser: !include includes/yandex_music_browser.yaml
automation: !include includes/automations.yaml

#Вынос в папки
#automation: !include_dir_merge_list includes/automations

#logger:
#  default: info
#  logs: { 
#    custom_components.yandex_station: debug, 
#    pygrocy.grocy_api_client: debug,
#    custom_components.grocy: debug
#    }